### ISSUE TITLE
提示logger not found in vuex?

### ISSUE THREAD

**Issue by lumixraku** [jangdelong/vue-blog-demo#1]
提示logger not found in vuex?
升级了vuex 并且 改为 import createLogger from 'vuex/dist/logger'  才OK   
这是为什么呢?

**Comment by jangdelong** [comment]
你用的vue版本是什么版本呢？

**Comment by lumixraku** [comment]
啊 sorry  是我弄错了  我的vue是 1.x    vuex 弄成2.x 了....

**Comment by struggle-fish** [comment]
logger报错。直接干掉不用了。版本问题
